#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Software")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Software.Properties.Settings.Default.SoftwareConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BasicMaths_Insert")]
		public int BasicMaths_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BMPoints", DbType="Int")] System.Nullable<int> bMPoints)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, bMPoints);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Memo_PointsInsert")]
		public int Memo_PointsInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MMPoints", DbType="Int")] System.Nullable<int> mMPoints)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, mMPoints);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Puzzle_PointsInsert")]
		public int Puzzle_PointsInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PZPoints", DbType="Int")] System.Nullable<int> pZPoints, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PZTime", DbType="VarChar(15)")] string pZTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, pZPoints, pZTime);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
